server:
  port: 8081

spring:
  application:
    name: chat-server

jwt:
  token:
    header: Authorization
    issuer: ${spring.application.name}
    secret: aHdhbnNlLXNwcmluZy1zZWN1cml0eS1qd3QtYXV0aC1zZXJ2ZXItc2VjcmV0LWtleQo=
    expiration: 3600